# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RDB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RDB

  target 'RDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'AFNetworking', '~> 3.0'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'GoogleSignIn'
pod 'PNChart'

end
